//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.Entities.Data
{
    using System;
    using System.Collections.Generic;

    public partial class Reservation
    {
        public int ReservationNr { get; set; }
        public string Name { get; set; }
        public int PhoneNr { get; set; }
        public decimal Price { get; set; }
        public int TicketId { get; set; }

        public virtual Ticket Ticket { get; set; }


    }
}
