//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.Entities.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public Room()
        {
            this.Seats = new HashSet<Seat>();
            this.TimeTables = new HashSet<TimeTable>();
        }
    
        public int RoomId { get; set; }
        public string RoomName { get; set; }
    
        public virtual ICollection<Seat> Seats { get; set; }
        public virtual ICollection<TimeTable> TimeTables { get; set; }
    }
}
