//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.Entities.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seat
    {
        public Seat()
        {
            this.Tickets = new HashSet<Ticket>();
        }
    
        public decimal SeatNr { get; set; }
        public bool Reserved { get; set; }
        public bool Paid { get; set; }
        public decimal RowNr { get; set; }
        public int RoomId { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
