//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.Entities.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTable
    {
        public TimeTable()
        {
            this.Tickets = new HashSet<Ticket>();
        }
    
        public int TimeTableId { get; set; }
        public System.DateTime StartTime { get; set; }
        public int MovieId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int RoomId { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
